=== hivemq/hivemq-mqtt-message-log-extension/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Copyright 2019-present HiveMQ GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hivemq-mqtt-message-log-extension" type="PropertyEntity"/>
    <xs:complexType name="PropertyEntity">
        <xs:all>
            <xs:element name="verbose" type="xs:boolean" minOccurs="0"/>
            <xs:element name="payload" type="xs:boolean" minOccurs="0"/>
            <xs:element name="passwordinverbose" type="xs:boolean" minOccurs="0"/>
            <xs:element name="publish-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="publish-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="client-connect" type="xs:boolean" minOccurs="0"/>
            <xs:element name="connack-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="client-disconnect" type="xs:boolean" minOccurs="0"/>
            <xs:element name="subscribe-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="suback-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="unsubscribe-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="unsuback-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="ping-request-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="ping-response-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="puback-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="puback-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubrec-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubrec-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubrel-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubrel-send" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubcomp-received" type="xs:boolean" minOccurs="0"/>
            <xs:element name="pubcomp-send" type="xs:boolean" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

</xs:schema>

=== hivemq/hivemq-mqtt-message-log-extension/src/hivemq-extension/conf/examples/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hivemq-mqtt-message-log-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                   xsi:noNamespaceSchemaLocation="config.xsd">
    <!--
    Example properties file that will prevent the logging of
    both incoming and outgoing messages, but all other
    events, such as connection and subscription events, will be logged.
    -->
    <!--General settings-->
    <verbose>false</verbose>
    <payload>true</payload>
    <json>false</json>

    <!--Event settings-->
    <publish-received>false</publish-received>
    <publish-send>false</publish-send>

    <client-connect>true</client-connect>
    <connack-send>true</connack-send>
    <client-disconnect>true</client-disconnect>
    <subscribe-received>true</subscribe-received>
    <suback-send>true</suback-send>
    <unsubscribe-received>true</unsubscribe-received>
    <unsuback-send>true</unsuback-send>
    <ping-request-received>true</ping-request-received>
    <ping-response-send>true</ping-response-send>
    <puback-received>true</puback-received>
    <puback-send>true</puback-send>
    <pubrec-received>true</pubrec-received>
    <pubrec-send>true</pubrec-send>
    <pubrel-received>true</pubrel-received>
    <pubrel-send>true</pubrel-send>
    <pubcomp-received>true</pubcomp-received>
    <pubcomp-send>true</pubcomp-send>

</hivemq-mqtt-message-log-extension>
